package mx.trillas.seguimientoembarques.persitence.pojos;

// Generated 28/10/2015 05:40:55 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Almacen generated by hbm2java
 */
public class Almacen implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2015060618271451296L;

    private int clave;
    private String nombre;
    private String seriefacturacion;
    private String seriedevolucion;
    private String seriecredito;
    private String seriesimple;
    private Character caracter;
    private Set useralmacens = new HashSet(0);

   public Almacen() {
   }

	
   public Almacen(int clave, String nombre) {
       this.clave = clave;
       this.nombre = nombre;
   }
   public Almacen(int clave, String nombre, String seriefacturacion, String seriedevolucion, String seriecredito, String seriesimple, Character caracter, Set useralmacens) {
      this.clave = clave;
      this.nombre = nombre;
      this.seriefacturacion = seriefacturacion;
      this.seriedevolucion = seriedevolucion;
      this.seriecredito = seriecredito;
      this.seriesimple = seriesimple;
      this.caracter = caracter;
      this.useralmacens = useralmacens;
   }
  
   public int getClave() {
       return this.clave;
   }
   
   public void setClave(int clave) {
       this.clave = clave;
   }
   public String getNombre() {
       return this.nombre;
   }
   
   public void setNombre(String nombre) {
       this.nombre = nombre;
   }
   public String getSeriefacturacion() {
       return this.seriefacturacion;
   }
   
   public void setSeriefacturacion(String seriefacturacion) {
       this.seriefacturacion = seriefacturacion;
   }
   public String getSeriedevolucion() {
       return this.seriedevolucion;
   }
   
   public void setSeriedevolucion(String seriedevolucion) {
       this.seriedevolucion = seriedevolucion;
   }
   public String getSeriecredito() {
       return this.seriecredito;
   }
   
   public void setSeriecredito(String seriecredito) {
       this.seriecredito = seriecredito;
   }
   public String getSeriesimple() {
       return this.seriesimple;
   }
   
   public void setSeriesimple(String seriesimple) {
       this.seriesimple = seriesimple;
   }
   public Character getCaracter() {
       return this.caracter;
   }
   
   public void setCaracter(Character caracter) {
       this.caracter = caracter;
   }
   public Set getUseralmacens() {
       return this.useralmacens;
   }
   
   public void setUseralmacens(Set useralmacens) {
       this.useralmacens = useralmacens;
   }

   public String toString(){
	   return this.getNombre() + "  ";
   }
   
	@Override
	public boolean equals(Object obj) {
		if (obj == null)
			return false;
		if (!(obj instanceof Almacen))
			return false;
		Almacen otroAlmacen = (Almacen) obj;
		if (this.clave != otroAlmacen.getClave())
			return false;
		if (!this.nombre.equals(otroAlmacen.getNombre()))
			return false;
		return true;
	}
}
