package mx.trillas.seguimientoembarques.persitence.pojos;
// Generated 28/10/2015 05:40:55 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipousuario generated by hbm2java
 */
public class Tipousuario  implements java.io.Serializable {


     private String tipo;
     private Set usuarios = new HashSet(0);

    public Tipousuario() {
    }

	
    public Tipousuario(String tipo) {
        this.tipo = tipo;
    }
    public Tipousuario(String tipo, Set usuarios) {
       this.tipo = tipo;
       this.usuarios = usuarios;
    }
   
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }


    @Override
    public boolean equals(Object object){
    	if(object ==null)return false;
    	if(!(object instanceof Tipousuario))return false;
    	Tipousuario tipoUsuario=(Tipousuario)object;
    	if(!this.getTipo().equals(tipoUsuario.getTipo()))return false;
    	return true;
    }

}


