package mx.trillas.seguimientoembarques.persitence.pojos;
// Generated 28/10/2015 05:40:55 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * UserAlmacen generated by hbm2java
 */
public class UserAlmacen  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
     private Almacen almacen;
     private Usuario usuario;
     private Date modificacion;
     private Date creacion;

    public UserAlmacen() {
    }

	
    public UserAlmacen(int id, Almacen almacen, Usuario usuario) {
        this.id = id;
        this.almacen = almacen;
        this.usuario = usuario;
    }
    public UserAlmacen(int id, Almacen almacen, Usuario usuario, Date modificacion, Date creacion) {
       this.id = id;
       this.almacen = almacen;
       this.usuario = usuario;
       this.modificacion = modificacion;
       this.creacion = creacion;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Almacen getAlmacen() {
        return this.almacen;
    }
    
    public void setAlmacen(Almacen almacen) {
        this.almacen = almacen;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getModificacion() {
        return this.modificacion;
    }
    
    public void setModificacion(Date modificacion) {
        this.modificacion = modificacion;
    }
    public Date getCreacion() {
        return this.creacion;
    }
    
    public void setCreacion(Date creacion) {
        this.creacion = creacion;
    }

    @Override
	public boolean equals(Object obj) {
		if (obj == null)
			return false;
		if (!(obj instanceof UserAlmacen))
			return false;
		UserAlmacen otroAlmacen = (UserAlmacen) obj;
		
		if (this.usuario.equals(otroAlmacen.getUsuario()))
			return false;
		if (!this.almacen.equals(otroAlmacen.getAlmacen()))
			return false;
		return true;
	}


}


