package mx.trillas.seguimientoembarques.persitence.pojos;
// Generated 11/03/2016 11:14:06 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -1168551339452847707L;
	private String username;
     private Tipousuario tipousuario;
     private String name;
     private String password;
     private Set<?> useralmacens = new HashSet<>(0);

    public Usuario() {
    }

    public Usuario(String username, Tipousuario tipousuario) {
        this.username = username;
        this.tipousuario = tipousuario;
    }
	
    public Usuario(String username, Tipousuario tipousuario, String name) {
        this.username = username;
        this.tipousuario = tipousuario;
        this.name = name;
    }
    public Usuario(String username, Tipousuario tipousuario, String name, String password, Set<?> useralmacens) {
       this.username = username;
       this.tipousuario = tipousuario;
       this.name = name;
       this.password = password;
       this.useralmacens = useralmacens;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public Tipousuario getTipousuario() {
        return this.tipousuario;
    }
    
    public void setTipousuario(Tipousuario tipousuario) {
        this.tipousuario = tipousuario;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set<?> getUseralmacens() {
        return this.useralmacens;
    }
    
    public void setUseralmacens(Set<?> useralmacens) {
        this.useralmacens = useralmacens;
    }




}


