package mx.trillas.seguimientoembarques.persitence.pojos;
// Generated 16/05/2016 12:09:04 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Ft91 generated by hbm2java
 */
public class Ft91  implements java.io.Serializable {


     private Ft91Id id;
     private String idsys;
     private Integer cte;
     private String razsoc;
     private Date fecemi;
     private Date horemi;
     private Date fereal;
     private Date horeal;
     private String usreal;
     private Date fesaal;
     private Date hosall;
     private String ussal;
     private Date fereem;
     private Date horeem;
     private String usreem;
     private Date fesaem;
     private Date horsaem;
     private String ussaem;
     private Date fereeb;
     private Date horeeb;
     private String usreeb;
     private Date fesaeb;
     private Date hosaeb;
     private String ussaeb;
     private String pedido;
     private Integer cvecon;
     private Integer alma;
     private String cve;
     private String status;
     private Integer folini;
     private Integer folfin;
     private Integer cvv;
     private Integer tvta;
     private Date fdoc;
     private Date hdoc;
     private String perrec;
     private String ser;
     private Integer folio;
     private String carta;
     private String guia;
     private String placa;
     private String nomrec;
     private Date fesae2;
     private Date hosa32;
     private String ussae2;
     private Date fesae3;
     private Date hosae3;
     private String ussae3;
     private Date fesae4;
     private Date hosae4;
     private String ussae4;
     private Date fecenv;
     private Integer cutra;
     private Integer almad;
     private String serped;
     private Integer numped;
     private Date fecped;
     private String sertra;
     private Integer foltra;

    public Ft91() {
    }

	
    public Ft91(Ft91Id id) {
        this.id = id;
    }
    public Ft91(Ft91Id id, String idsys, Integer cte, String razsoc, Date fecemi, Date horemi, Date fereal, Date horeal, String usreal, Date fesaal, Date hosall, String ussal, Date fereem, Date horeem, String usreem, Date fesaem, Date horsaem, String ussaem, Date fereeb, Date horeeb, String usreeb, Date fesaeb, Date hosaeb, String ussaeb, String pedido, Integer cvecon, Integer alma, String cve, String status, Integer folini, Integer folfin, Integer cvv, Integer tvta, Date fdoc, Date hdoc, String perrec, String ser, Integer folio, String carta, String guia, String placa, String nomrec, Date fesae2, Date hosa32, String ussae2, Date fesae3, Date hosae3, String ussae3, Date fesae4, Date hosae4, String ussae4, Date fecenv, Integer cutra, Integer almad, String serped, Integer numped, Date fecped, String sertra, Integer foltra) {
       this.id = id;
       this.idsys = idsys;
       this.cte = cte;
       this.razsoc = razsoc;
       this.fecemi = fecemi;
       this.horemi = horemi;
       this.fereal = fereal;
       this.horeal = horeal;
       this.usreal = usreal;
       this.fesaal = fesaal;
       this.hosall = hosall;
       this.ussal = ussal;
       this.fereem = fereem;
       this.horeem = horeem;
       this.usreem = usreem;
       this.fesaem = fesaem;
       this.horsaem = horsaem;
       this.ussaem = ussaem;
       this.fereeb = fereeb;
       this.horeeb = horeeb;
       this.usreeb = usreeb;
       this.fesaeb = fesaeb;
       this.hosaeb = hosaeb;
       this.ussaeb = ussaeb;
       this.pedido = pedido;
       this.cvecon = cvecon;
       this.alma = alma;
       this.cve = cve;
       this.status = status;
       this.folini = folini;
       this.folfin = folfin;
       this.cvv = cvv;
       this.tvta = tvta;
       this.fdoc = fdoc;
       this.hdoc = hdoc;
       this.perrec = perrec;
       this.ser = ser;
       this.folio = folio;
       this.carta = carta;
       this.guia = guia;
       this.placa = placa;
       this.nomrec = nomrec;
       this.fesae2 = fesae2;
       this.hosa32 = hosa32;
       this.ussae2 = ussae2;
       this.fesae3 = fesae3;
       this.hosae3 = hosae3;
       this.ussae3 = ussae3;
       this.fesae4 = fesae4;
       this.hosae4 = hosae4;
       this.ussae4 = ussae4;
       this.fecenv = fecenv;
       this.cutra = cutra;
       this.almad = almad;
       this.serped = serped;
       this.numped = numped;
       this.fecped = fecped;
       this.sertra = sertra;
       this.foltra = foltra;
    }
   
    public Ft91Id getId() {
        return this.id;
    }
    
    public void setId(Ft91Id id) {
        this.id = id;
    }
    public String getIdsys() {
        return this.idsys;
    }
    
    public void setIdsys(String idsys) {
        this.idsys = idsys;
    }
    public Integer getCte() {
        return this.cte;
    }
    
    public void setCte(Integer cte) {
        this.cte = cte;
    }
    public String getRazsoc() {
        return this.razsoc;
    }
    
    public void setRazsoc(String razsoc) {
        this.razsoc = razsoc;
    }
    public Date getFecemi() {
        return this.fecemi;
    }
    
    public void setFecemi(Date fecemi) {
        this.fecemi = fecemi;
    }
    public Date getHoremi() {
        return this.horemi;
    }
    
    public void setHoremi(Date horemi) {
        this.horemi = horemi;
    }
    public Date getFereal() {
        return this.fereal;
    }
    
    public void setFereal(Date fereal) {
        this.fereal = fereal;
    }
    public Date getHoreal() {
        return this.horeal;
    }
    
    public void setHoreal(Date horeal) {
        this.horeal = horeal;
    }
    public String getUsreal() {
        return this.usreal;
    }
    
    public void setUsreal(String usreal) {
        this.usreal = usreal;
    }
    public Date getFesaal() {
        return this.fesaal;
    }
    
    public void setFesaal(Date fesaal) {
        this.fesaal = fesaal;
    }
    public Date getHosall() {
        return this.hosall;
    }
    
    public void setHosall(Date hosall) {
        this.hosall = hosall;
    }
    public String getUssal() {
        return this.ussal;
    }
    
    public void setUssal(String ussal) {
        this.ussal = ussal;
    }
    public Date getFereem() {
        return this.fereem;
    }
    
    public void setFereem(Date fereem) {
        this.fereem = fereem;
    }
    public Date getHoreem() {
        return this.horeem;
    }
    
    public void setHoreem(Date horeem) {
        this.horeem = horeem;
    }
    public String getUsreem() {
        return this.usreem;
    }
    
    public void setUsreem(String usreem) {
        this.usreem = usreem;
    }
    public Date getFesaem() {
        return this.fesaem;
    }
    
    public void setFesaem(Date fesaem) {
        this.fesaem = fesaem;
    }
    public Date getHorsaem() {
        return this.horsaem;
    }
    
    public void setHorsaem(Date horsaem) {
        this.horsaem = horsaem;
    }
    public String getUssaem() {
        return this.ussaem;
    }
    
    public void setUssaem(String ussaem) {
        this.ussaem = ussaem;
    }
    public Date getFereeb() {
        return this.fereeb;
    }
    
    public void setFereeb(Date fereeb) {
        this.fereeb = fereeb;
    }
    public Date getHoreeb() {
        return this.horeeb;
    }
    
    public void setHoreeb(Date horeeb) {
        this.horeeb = horeeb;
    }
    public String getUsreeb() {
        return this.usreeb;
    }
    
    public void setUsreeb(String usreeb) {
        this.usreeb = usreeb;
    }
    public Date getFesaeb() {
        return this.fesaeb;
    }
    
    public void setFesaeb(Date fesaeb) {
        this.fesaeb = fesaeb;
    }
    public Date getHosaeb() {
        return this.hosaeb;
    }
    
    public void setHosaeb(Date hosaeb) {
        this.hosaeb = hosaeb;
    }
    public String getUssaeb() {
        return this.ussaeb;
    }
    
    public void setUssaeb(String ussaeb) {
        this.ussaeb = ussaeb;
    }
    public String getPedido() {
        return this.pedido;
    }
    
    public void setPedido(String pedido) {
        this.pedido = pedido;
    }
    public Integer getCvecon() {
        return this.cvecon;
    }
    
    public void setCvecon(Integer cvecon) {
        this.cvecon = cvecon;
    }
    public Integer getAlma() {
        return this.alma;
    }
    
    public void setAlma(Integer alma) {
        this.alma = alma;
    }
    public String getCve() {
        return this.cve;
    }
    
    public void setCve(String cve) {
        this.cve = cve;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Integer getFolini() {
        return this.folini;
    }
    
    public void setFolini(Integer folini) {
        this.folini = folini;
    }
    public Integer getFolfin() {
        return this.folfin;
    }
    
    public void setFolfin(Integer folfin) {
        this.folfin = folfin;
    }
    public Integer getCvv() {
        return this.cvv;
    }
    
    public void setCvv(Integer cvv) {
        this.cvv = cvv;
    }
    public Integer getTvta() {
        return this.tvta;
    }
    
    public void setTvta(Integer tvta) {
        this.tvta = tvta;
    }
    public Date getFdoc() {
        return this.fdoc;
    }
    
    public void setFdoc(Date fdoc) {
        this.fdoc = fdoc;
    }
    public Date getHdoc() {
        return this.hdoc;
    }
    
    public void setHdoc(Date hdoc) {
        this.hdoc = hdoc;
    }
    public String getPerrec() {
        return this.perrec;
    }
    
    public void setPerrec(String perrec) {
        this.perrec = perrec;
    }
    public String getSer() {
        return this.ser;
    }
    
    public void setSer(String ser) {
        this.ser = ser;
    }
    public Integer getFolio() {
        return this.folio;
    }
    
    public void setFolio(Integer folio) {
        this.folio = folio;
    }
    public String getCarta() {
        return this.carta;
    }
    
    public void setCarta(String carta) {
        this.carta = carta;
    }
    public String getGuia() {
        return this.guia;
    }
    
    public void setGuia(String guia) {
        this.guia = guia;
    }
    public String getPlaca() {
        return this.placa;
    }
    
    public void setPlaca(String placa) {
        this.placa = placa;
    }
    public String getNomrec() {
        return this.nomrec;
    }
    
    public void setNomrec(String nomrec) {
        this.nomrec = nomrec;
    }
    public Date getFesae2() {
        return this.fesae2;
    }
    
    public void setFesae2(Date fesae2) {
        this.fesae2 = fesae2;
    }
    public Date getHosa32() {
        return this.hosa32;
    }
    
    public void setHosa32(Date hosa32) {
        this.hosa32 = hosa32;
    }
    public String getUssae2() {
        return this.ussae2;
    }
    
    public void setUssae2(String ussae2) {
        this.ussae2 = ussae2;
    }
    public Date getFesae3() {
        return this.fesae3;
    }
    
    public void setFesae3(Date fesae3) {
        this.fesae3 = fesae3;
    }
    public Date getHosae3() {
        return this.hosae3;
    }
    
    public void setHosae3(Date hosae3) {
        this.hosae3 = hosae3;
    }
    public String getUssae3() {
        return this.ussae3;
    }
    
    public void setUssae3(String ussae3) {
        this.ussae3 = ussae3;
    }
    public Date getFesae4() {
        return this.fesae4;
    }
    
    public void setFesae4(Date fesae4) {
        this.fesae4 = fesae4;
    }
    public Date getHosae4() {
        return this.hosae4;
    }
    
    public void setHosae4(Date hosae4) {
        this.hosae4 = hosae4;
    }
    public String getUssae4() {
        return this.ussae4;
    }
    
    public void setUssae4(String ussae4) {
        this.ussae4 = ussae4;
    }
    public Date getFecenv() {
        return this.fecenv;
    }
    
    public void setFecenv(Date fecenv) {
        this.fecenv = fecenv;
    }
    public Integer getCutra() {
        return this.cutra;
    }
    
    public void setCutra(Integer cutra) {
        this.cutra = cutra;
    }
    public Integer getAlmad() {
        return this.almad;
    }
    
    public void setAlmad(Integer almad) {
        this.almad = almad;
    }
    public String getSerped() {
        return this.serped;
    }
    
    public void setSerped(String serped) {
        this.serped = serped;
    }
    public Integer getNumped() {
        return this.numped;
    }
    
    public void setNumped(Integer numped) {
        this.numped = numped;
    }
    public Date getFecped() {
        return this.fecped;
    }
    
    public void setFecped(Date fecped) {
        this.fecped = fecped;
    }
    public String getSertra() {
        return this.sertra;
    }
    
    public void setSertra(String sertra) {
        this.sertra = sertra;
    }
    public Integer getFoltra() {
        return this.foltra;
    }
    
    public void setFoltra(Integer foltra) {
        this.foltra = foltra;
    }




}


