package mx.trillas.seguimientoembarques.persitence.pojos;
// Generated 22/06/2016 03:58:43 PM by Hibernate Tools 4.3.1



/**
 * Ft96Id generated by hbm2java
 */
public class Ft96Id  implements java.io.Serializable {


     private String ser;
     private int folio;

    public Ft96Id() {
    }

    public Ft96Id(String ser, int folio) {
       this.ser = ser;
       this.folio = folio;
    }
   
    public String getSer() {
        return this.ser;
    }
    
    public void setSer(String ser) {
        this.ser = ser;
    }
    public int getFolio() {
        return this.folio;
    }
    
    public void setFolio(int folio) {
        this.folio = folio;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Ft96Id) ) return false;
		 Ft96Id castOther = ( Ft96Id ) other; 
         
		 return ( (this.getSer()==castOther.getSer()) || ( this.getSer()!=null && castOther.getSer()!=null && this.getSer().equals(castOther.getSer()) ) )
 && (this.getFolio()==castOther.getFolio());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSer() == null ? 0 : this.getSer().hashCode() );
         result = 37 * result + this.getFolio();
         return result;
   }   


}


