package mx.trillas.seguimientoembarques.persitence.pojos;
// Generated 16/05/2016 10:04:39 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Ft96 generated by hbm2java
 */
public class Ft96  implements java.io.Serializable {


     private Ft96Id id;
     private String ident;
     private String ctrl;
     private Integer tipodoc;
     private String sta;
     private String f1;
     private String rsocf;
     private String dirf;
     private String colf;
     private String delf;
     private String cdf;
     private String edof;
     private String paisf;
     private Integer cpf;
     private String f2;
     private String rsoce;
     private String dire;
     private String cole;
     private String dele;
     private String cde;
     private String edoe;
     private String paise;
     private Integer cpe;
     private String f3;
     private Integer cta;
     private Integer tunid;
     private Double timpnm;
     private Double timpdl;
     private Integer tdoc;
     private String f4;
     private Integer cvtra;
     private String ciatra;
     private String guia;
     private Date fecenv;
     private Integer ncaj;
     private Integer npac;
     private String placas;
     private String nomrec;
     private String trep;
     private String folpas;
     private String f5;
     private Date feccap;
     private Date horcap;
     private String sucap;
     private Date horenv;
     private String f6;
     private String facpa12g;
     private String faccan;
     private Double impfle;
     private Double impseg;
     private Double imtot;
     private String nordco;
     private String nconre;
     private String ndevo;
     private Integer relemp;
     private Integer origi;
     private Integer carins;
     private Integer pagcaj;
     private Integer cpama;
     private Integer idoper;
     private String idootr;

    public Ft96() {
    }

	
    public Ft96(Ft96Id id) {
        this.id = id;
    }
    public Ft96(Ft96Id id, String ident, String ctrl, Integer tipodoc, String sta, String f1, String rsocf, String dirf, String colf, String delf, String cdf, String edof, String paisf, Integer cpf, String f2, String rsoce, String dire, String cole, String dele, String cde, String edoe, String paise, Integer cpe, String f3, Integer cta, Integer tunid, Double timpnm, Double timpdl, Integer tdoc, String f4, Integer cvtra, String ciatra, String guia, Date fecenv, Integer ncaj, Integer npac, String placas, String nomrec, String trep, String folpas, String f5, Date feccap, Date horcap, String sucap, Date horenv, String f6, String facpa12g, String faccan, Double impfle, Double impseg, Double imtot, String nordco, String nconre, String ndevo, Integer relemp, Integer origi, Integer carins, Integer pagcaj, Integer cpama, Integer idoper, String idootr) {
       this.id = id;
       this.ident = ident;
       this.ctrl = ctrl;
       this.tipodoc = tipodoc;
       this.sta = sta;
       this.f1 = f1;
       this.rsocf = rsocf;
       this.dirf = dirf;
       this.colf = colf;
       this.delf = delf;
       this.cdf = cdf;
       this.edof = edof;
       this.paisf = paisf;
       this.cpf = cpf;
       this.f2 = f2;
       this.rsoce = rsoce;
       this.dire = dire;
       this.cole = cole;
       this.dele = dele;
       this.cde = cde;
       this.edoe = edoe;
       this.paise = paise;
       this.cpe = cpe;
       this.f3 = f3;
       this.cta = cta;
       this.tunid = tunid;
       this.timpnm = timpnm;
       this.timpdl = timpdl;
       this.tdoc = tdoc;
       this.f4 = f4;
       this.cvtra = cvtra;
       this.ciatra = ciatra;
       this.guia = guia;
       this.fecenv = fecenv;
       this.ncaj = ncaj;
       this.npac = npac;
       this.placas = placas;
       this.nomrec = nomrec;
       this.trep = trep;
       this.folpas = folpas;
       this.f5 = f5;
       this.feccap = feccap;
       this.horcap = horcap;
       this.sucap = sucap;
       this.horenv = horenv;
       this.f6 = f6;
       this.facpa12g = facpa12g;
       this.faccan = faccan;
       this.impfle = impfle;
       this.impseg = impseg;
       this.imtot = imtot;
       this.nordco = nordco;
       this.nconre = nconre;
       this.ndevo = ndevo;
       this.relemp = relemp;
       this.origi = origi;
       this.carins = carins;
       this.pagcaj = pagcaj;
       this.cpama = cpama;
       this.idoper = idoper;
       this.idootr = idootr;
    }
   
    public Ft96Id getId() {
        return this.id;
    }
    
    public void setId(Ft96Id id) {
        this.id = id;
    }
    public String getIdent() {
        return this.ident;
    }
    
    public void setIdent(String ident) {
        this.ident = ident;
    }
    public String getCtrl() {
        return this.ctrl;
    }
    
    public void setCtrl(String ctrl) {
        this.ctrl = ctrl;
    }
    public Integer getTipodoc() {
        return this.tipodoc;
    }
    
    public void setTipodoc(Integer tipodoc) {
        this.tipodoc = tipodoc;
    }
    public String getSta() {
        return this.sta;
    }
    
    public void setSta(String sta) {
        this.sta = sta;
    }
    public String getF1() {
        return this.f1;
    }
    
    public void setF1(String f1) {
        this.f1 = f1;
    }
    public String getRsocf() {
        return this.rsocf;
    }
    
    public void setRsocf(String rsocf) {
        this.rsocf = rsocf;
    }
    public String getDirf() {
        return this.dirf;
    }
    
    public void setDirf(String dirf) {
        this.dirf = dirf;
    }
    public String getColf() {
        return this.colf;
    }
    
    public void setColf(String colf) {
        this.colf = colf;
    }
    public String getDelf() {
        return this.delf;
    }
    
    public void setDelf(String delf) {
        this.delf = delf;
    }
    public String getCdf() {
        return this.cdf;
    }
    
    public void setCdf(String cdf) {
        this.cdf = cdf;
    }
    public String getEdof() {
        return this.edof;
    }
    
    public void setEdof(String edof) {
        this.edof = edof;
    }
    public String getPaisf() {
        return this.paisf;
    }
    
    public void setPaisf(String paisf) {
        this.paisf = paisf;
    }
    public Integer getCpf() {
        return this.cpf;
    }
    
    public void setCpf(Integer cpf) {
        this.cpf = cpf;
    }
    public String getF2() {
        return this.f2;
    }
    
    public void setF2(String f2) {
        this.f2 = f2;
    }
    public String getRsoce() {
        return this.rsoce;
    }
    
    public void setRsoce(String rsoce) {
        this.rsoce = rsoce;
    }
    public String getDire() {
        return this.dire;
    }
    
    public void setDire(String dire) {
        this.dire = dire;
    }
    public String getCole() {
        return this.cole;
    }
    
    public void setCole(String cole) {
        this.cole = cole;
    }
    public String getDele() {
        return this.dele;
    }
    
    public void setDele(String dele) {
        this.dele = dele;
    }
    public String getCde() {
        return this.cde;
    }
    
    public void setCde(String cde) {
        this.cde = cde;
    }
    public String getEdoe() {
        return this.edoe;
    }
    
    public void setEdoe(String edoe) {
        this.edoe = edoe;
    }
    public String getPaise() {
        return this.paise;
    }
    
    public void setPaise(String paise) {
        this.paise = paise;
    }
    public Integer getCpe() {
        return this.cpe;
    }
    
    public void setCpe(Integer cpe) {
        this.cpe = cpe;
    }
    public String getF3() {
        return this.f3;
    }
    
    public void setF3(String f3) {
        this.f3 = f3;
    }
    public Integer getCta() {
        return this.cta;
    }
    
    public void setCta(Integer cta) {
        this.cta = cta;
    }
    public Integer getTunid() {
        return this.tunid;
    }
    
    public void setTunid(Integer tunid) {
        this.tunid = tunid;
    }
    public Double getTimpnm() {
        return this.timpnm;
    }
    
    public void setTimpnm(Double timpnm) {
        this.timpnm = timpnm;
    }
    public Double getTimpdl() {
        return this.timpdl;
    }
    
    public void setTimpdl(Double timpdl) {
        this.timpdl = timpdl;
    }
    public Integer getTdoc() {
        return this.tdoc;
    }
    
    public void setTdoc(Integer tdoc) {
        this.tdoc = tdoc;
    }
    public String getF4() {
        return this.f4;
    }
    
    public void setF4(String f4) {
        this.f4 = f4;
    }
    public Integer getCvtra() {
        return this.cvtra;
    }
    
    public void setCvtra(Integer cvtra) {
        this.cvtra = cvtra;
    }
    public String getCiatra() {
        return this.ciatra;
    }
    
    public void setCiatra(String ciatra) {
        this.ciatra = ciatra;
    }
    public String getGuia() {
        return this.guia;
    }
    
    public void setGuia(String guia) {
        this.guia = guia;
    }
    public Date getFecenv() {
        return this.fecenv;
    }
    
    public void setFecenv(Date fecenv) {
        this.fecenv = fecenv;
    }
    public Integer getNcaj() {
        return this.ncaj;
    }
    
    public void setNcaj(Integer ncaj) {
        this.ncaj = ncaj;
    }
    public Integer getNpac() {
        return this.npac;
    }
    
    public void setNpac(Integer npac) {
        this.npac = npac;
    }
    public String getPlacas() {
        return this.placas;
    }
    
    public void setPlacas(String placas) {
        this.placas = placas;
    }
    public String getNomrec() {
        return this.nomrec;
    }
    
    public void setNomrec(String nomrec) {
        this.nomrec = nomrec;
    }
    public String getTrep() {
        return this.trep;
    }
    
    public void setTrep(String trep) {
        this.trep = trep;
    }
    public String getFolpas() {
        return this.folpas;
    }
    
    public void setFolpas(String folpas) {
        this.folpas = folpas;
    }
    public String getF5() {
        return this.f5;
    }
    
    public void setF5(String f5) {
        this.f5 = f5;
    }
    public Date getFeccap() {
        return this.feccap;
    }
    
    public void setFeccap(Date feccap) {
        this.feccap = feccap;
    }
    public Date getHorcap() {
        return this.horcap;
    }
    
    public void setHorcap(Date horcap) {
        this.horcap = horcap;
    }
    public String getSucap() {
        return this.sucap;
    }
    
    public void setSucap(String sucap) {
        this.sucap = sucap;
    }
    public Date getHorenv() {
        return this.horenv;
    }
    
    public void setHorenv(Date horenv) {
        this.horenv = horenv;
    }
    public String getF6() {
        return this.f6;
    }
    
    public void setF6(String f6) {
        this.f6 = f6;
    }
    public String getFacpa12g() {
        return this.facpa12g;
    }
    
    public void setFacpa12g(String facpa12g) {
        this.facpa12g = facpa12g;
    }
    public String getFaccan() {
        return this.faccan;
    }
    
    public void setFaccan(String faccan) {
        this.faccan = faccan;
    }
    public Double getImpfle() {
        return this.impfle;
    }
    
    public void setImpfle(Double impfle) {
        this.impfle = impfle;
    }
    public Double getImpseg() {
        return this.impseg;
    }
    
    public void setImpseg(Double impseg) {
        this.impseg = impseg;
    }
    public Double getImtot() {
        return this.imtot;
    }
    
    public void setImtot(Double imtot) {
        this.imtot = imtot;
    }
    public String getNordco() {
        return this.nordco;
    }
    
    public void setNordco(String nordco) {
        this.nordco = nordco;
    }
    public String getNconre() {
        return this.nconre;
    }
    
    public void setNconre(String nconre) {
        this.nconre = nconre;
    }
    public String getNdevo() {
        return this.ndevo;
    }
    
    public void setNdevo(String ndevo) {
        this.ndevo = ndevo;
    }
    public Integer getRelemp() {
        return this.relemp;
    }
    
    public void setRelemp(Integer relemp) {
        this.relemp = relemp;
    }
    public Integer getOrigi() {
        return this.origi;
    }
    
    public void setOrigi(Integer origi) {
        this.origi = origi;
    }
    public Integer getCarins() {
        return this.carins;
    }
    
    public void setCarins(Integer carins) {
        this.carins = carins;
    }
    public Integer getPagcaj() {
        return this.pagcaj;
    }
    
    public void setPagcaj(Integer pagcaj) {
        this.pagcaj = pagcaj;
    }
    public Integer getCpama() {
        return this.cpama;
    }
    
    public void setCpama(Integer cpama) {
        this.cpama = cpama;
    }
    public Integer getIdoper() {
        return this.idoper;
    }
    
    public void setIdoper(Integer idoper) {
        this.idoper = idoper;
    }
    public String getIdootr() {
        return this.idootr;
    }
    
    public void setIdootr(String idootr) {
        this.idootr = idootr;
    }




}


