package mx.trillas.seguimientoembarques.persitence.pojos;
// Generated 16/05/2016 10:04:39 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipousuario generated by hbm2java
 */
public class Tipousuario  implements java.io.Serializable {


     private String tipo;
     private Set usuarios = new HashSet(0);

    public Tipousuario() {
    }

	
    public Tipousuario(String tipo) {
        this.tipo = tipo;
    }
    public Tipousuario(String tipo, Set usuarios) {
       this.tipo = tipo;
       this.usuarios = usuarios;
    }
   
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }


	public boolean equals(Object obj) {
		if(obj==null)return false;
		if(!(obj instanceof Tipousuario))return false;
		Tipousuario tipousuario = (Tipousuario)obj;
		return this.tipo.equals(tipousuario.getTipo());
	}



}


